import { ResponseType, ResponseStatus, RapidResponse } from '@dms/shared';

export const seedResponses: RapidResponse[] = [
  {
    id: 'test-response-123',
    responseType: ResponseType.HEALTH,
    status: ResponseStatus.PLANNED,
    plannedDate: new Date('2024-08-25T10:00:00Z'),
    affectedEntityId: 'entity-1',
    assessmentId: 'assessment-1',
    responderId: 'responder-1',
    responderName: 'John Doe',
    verificationStatus: 'PENDING' as any,
    syncStatus: 'SYNCED' as any,
    data: {
      medicinesDelivered: [],
      medicalSuppliesDelivered: [],
      healthWorkersDeployed: 2,
      patientsTreated: 0,
    },
    otherItemsDelivered: [
      { item: 'Paracetamol', quantity: 100, unit: 'tablets' },
      { item: 'Bandages', quantity: 25, unit: 'rolls' },
    ],
    deliveryEvidence: [],
    createdAt: new Date('2024-08-24T08:00:00Z'),
    updatedAt: new Date('2024-08-24T08:00:00Z'),
  },
  {
    id: 'test-response-456',
    responseType: ResponseType.WASH,
    status: ResponseStatus.PLANNED,
    plannedDate: new Date('2024-08-25T14:00:00Z'),
    affectedEntityId: 'entity-2',
    assessmentId: 'assessment-2',
    responderId: 'responder-2',
    responderName: 'Jane Smith',
    verificationStatus: 'PENDING' as any,
    syncStatus: 'SYNCED' as any,
    data: {
      waterContainersDistributed: [],
      hygieneKitsDistributed: [],
      sanitationFacilitiesConstructed: 1,
      waterPointsEstablished: 2,
    },
    otherItemsDelivered: [
      { item: 'Water Containers', quantity: 50, unit: 'pieces' },
      { item: 'Hygiene Kits', quantity: 30, unit: 'kits' },
      { item: 'Water Purification Tablets', quantity: 100, unit: 'packets' },
    ],
    deliveryEvidence: [],
    createdAt: new Date('2024-08-24T09:00:00Z'),
    updatedAt: new Date('2024-08-24T09:00:00Z'),
  },
  {
    id: 'test-response-789',
    responseType: ResponseType.FOOD,
    status: ResponseStatus.PLANNED,
    plannedDate: new Date('2024-08-25T16:00:00Z'),
    affectedEntityId: 'entity-3',
    assessmentId: 'assessment-3',
    responderId: 'responder-3',
    responderName: 'Bob Wilson',
    verificationStatus: 'PENDING' as any,
    syncStatus: 'SYNCED' as any,
    data: {
      foodPackagesDistributed: [],
      cookingKitsDistributed: [],
      mealsServed: 0,
      nutritionScreeningsCompleted: 0,
    },
    otherItemsDelivered: [
      { item: 'Rice', quantity: 50, unit: 'kg' },
      { item: 'Cooking Oil', quantity: 10, unit: 'liters' },
      { item: 'Ready-to-Eat Meals', quantity: 100, unit: 'packets' },
    ],
    deliveryEvidence: [],
    createdAt: new Date('2024-08-24T10:00:00Z'),
    updatedAt: new Date('2024-08-24T10:00:00Z'),
  },
];